import { Container } from '@/styles'
import Head from 'next/head'

import arcane from '../images/giphy.gif'
import Image from 'next/image'
import Link from 'next/link'
import Loading from '@/components/loading'

export default function Home() {
  return (
    <Container>
      <Loading />
      <Head>
        <title>GameInfo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>
          Encontre informações <br></br> sobre seus <br></br> jogos preferidos aqui!
        </p>
        <Link href='../GamePage'>Start</Link>
      </div>
      <div>
      <figure>
        <Image src={arcane} width={1000} height={500}></Image>
      </figure>
      </div>
    </Container>
  )
}
